SMS Function Update
sngguojie/CZ3003-CMS pull request #8
Opened 2016-10-14 18:07 UTC by jiaqi1993

Why
Recreated PR.

Created a new Entity SMS with the SMS Function Implemented, Tested with PostMan Working,
But I've removed my password for the sms sending to prevent it from sending without my monitoring.

Postman Test on Agency, IncidentCallReport still working on.
How
implemented SMS using a requests python library.

Side Effects
SMS function working

2016-10-17 16:16 UTC, chinjieh requested changes
Stuff to change!

2016-10-17 16:16 UTC, chinjieh commented on CZ3003CMS/settings.py
> +<<<<<<< HEAD
There's a merge conflict (most likely during rebase) that is unresolved here, please resolve!

2016-10-17 16:16 UTC, chinjieh commented on Incident/migrations/0001_initial.py
> +<<<<<<< HEAD
Merge conflict here also

2016-10-17 16:16 UTC, chinjieh commented on SMS/views.py
> +		print "test"
I think `print` does not actually print to console when heroku server is running. Instead, it gets 'eaten' up and displayed only after server is shutdown, which is bad.

I actually setup a `logger` configuration, you can reference `IncidentLocation` to see how debug messages are logged. I think you use `logger.debug(_)` to log to console.

But anyway, if everything is working, we should not be posting debug logs to console anyway.

2016-10-18 16:29 UTC, chinjieh commented on SMS/views.py
> +		print "test"
Since we're on this PR, can settle this also?

2016-10-18 16:35 UTC, merged

2016-10-18 16:36 UTC, chinjieh commented
Oh oops I tried to fix the merge conflict with `master` and this branch, apparently Github automatically detects the PR as merged and closed. Ohwell, learning point for the future haha.

2016-10-18 16:37 UTC, chinjieh commented on SMS/views.py
> +		print "test"
Ok nevermind, since I accidentally merged it in. Could @jiaqi1993 settle this locally?

2016-10-18 17:01 UTC, jiaqi1993 commented on SMS/views.py
> +		print "test"
Ok